POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name":"Alberto Júnior",
    "email":"alberto.junior4@rocketseat.com.br"
}


###

GET http://localhost:3333/invites/87da54d2-b158-4f85-88e7-357f35c162b5